name: David Méndez
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8482922704424709
title: David Méndez
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8125
  lightness: 0.6789566569495946
  saturation: 0.7332264098804444
  rhythmicContrast: 0.23307000193744898
purpose: []
